version: '3.8'
services:
    backend:
        build:
            context: ./api
            args:
                JWT_SECRET: ${JWT_SECRET}
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        env_file: ./.env
        networks:
            - backend
            - frontend
    frontend:
        depends_on:
            - backend
        build:
            context: ./client
            args:
                VITE_API_BASE_URL: ${VITE_API_BASE_URL}
                VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
                JWT_SECRET: ${JWT_SECRET}
        ports:
            - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
        networks:
            - frontend

networks:
    backend:
    frontend: